version: "3.8"

services:
  django:
    build: .
    container_name: app

    ports:
      - "8080:8000"
    command: >
      sh -c "python manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000"